// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var Conntrack = NewRuntimeAsset("conntrack.c", "cb923bae885f1c01a6b963a616b12b35a4816867720e9bb39674b2b60470eca1")
