// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "7bc342aa2f30780258c304b2069035d1bb160f8efb17e1785a26620f251864a1")
